version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8001
    privileged: true
    image: chi_chinh
    command: gunicorn chi_chinh.wsgi:application --bind 0.0.0.0:8001 --workers=3
    volumes:
      - static:/home/app/web/staticfiles
      - media:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    networks:
      - app
      - proxy
    restart: unless-stopped

  dramatiq:
    image: chi_chinh
    command: python manage.py rundramatiq --settings=settings.prod
    env_file:
      - ./.env.prod
    networks:
      - app

  redis:
    command: ['redis-server', '/etc/redis/redis.conf']
    user: "1001"
    volumes:
      - redis_data:/var/libredis/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    networks:
      - app
    restart: always
    ports:
      - "6381:6381"

volumes:
  redis_data:
  static:
  media:

networks:
  app:
  proxy:
    external:
      name: nginx-proxy
