version: '3'

services:
  web:
    volumes:
      - ./:/app
    command: /bin/sh web.dev.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  dramatiq:
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chichinh
      - POSTGRES_PASSWORD=chichinh
      - POSTGRES_DB=chichinh_dev
  redis:
    ports:
      - "6380:6380"

volumes:
  postgres_data:
  app:
