# Generated by Django 3.0.5 on 2020-04-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='trigger',
            new_name='crontab',
        ),
    ]
