# Generated by Django 3.0.5 on 2020-04-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200430_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('crontab', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
