# Generated by Django 3.0.5 on 2020-04-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='date_posted',
            new_name='created',
        ),
    ]
